# Generated by Django 4.1.4 on 2022-12-09 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='edit_permissions',
            field=models.ManyToManyField(related_name='permitted_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
